### PR TITLE
Bugfix/fix listitem imports

### PR DESCRIPTION
**Pull request by mendlik**
Related with https://github.com/borela/react-toolbox-plus-router/issues/1

### CODE REVIEW

**Comment by mendlik** [comment]
Thanks for this lib. It will be a bit easier to contribute if you add some tests ;)

**Comment by borela** [comment]
I made this lib in a bit of hurry for a project, I'll add them later, but if you want I can give you commit rights so that you can make changes without pull requests.

**Comment by mendlik** [comment]
To be honest I'm in a hurry as well. Thanks for merging :)

**Comment by mendlik** [comment]
Something is wrong I just got version 1.1.1 from npm and there still is `react-toolbox/lib/ListItemLayout.js` instead of `react-toolbox/lib/list/ListItemLayout.js`

**Comment by mendlik** [comment]
I just checked it with `npm pack react-toolbox-plus-router`.
Seems that my changes did not go to npmjs.

**Comment by borela** [comment]
My bad, I had merged with the local HEAD before -.-, I definitely need to sleep... Published the version with your patch.

**Comment by mendlik** [comment]
Thanks a lot :)

**Pull request merged**
